"""Defines context management tools"""

import os
from langchain_chroma import Chroma
from langchain_core.messages import HumanMessage
from langchain_text_splitters import RecursiveCharacterTextSplitter, Language

from src.agent import runtime_config
from src.agent.llm import llm
from src.agent.prompt import (
    RELEVANT_FILE_EXPLANATION_SYSTEM_PROMPT,
)
from src.agent.runtime_config import load_env_config
from src.agent.tool_set.stf_embeddings import STEmbeddings
from pydantic import BaseModel, Field
from typing import Literal
from langchain_core.tools import tool

load_env_config()

SEARCH_PROMPTS: dict = {
    "general": "Instruct: Retrieve code or text based on user query\nQuery: ",
    "originalbug": "Instruct: Given a bug description, retrieve codes that need to be edited to resolve it.\nQuery: ",
    "llmsummary": "Instruct: Given a summary of bug description generated by an LLM, retrieve codes that need to be edited to resolve it.\nQuery: ",
}


EMBEDDING_FUNCTIONS_BY_SEARCH_MODEL = {
    name: STEmbeddings(
        model_name="",
        device="cpu",
        query_prompt=SEARCH_PROMPTS[name],
        trust_remote_code=True,
        local_files_only=True
    )
    for name in SEARCH_PROMPTS.keys()
}

PROJECT_KNOWLEDGE_TEXT_SPLITTER = RecursiveCharacterTextSplitter.from_language(
    language=Language.PYTHON,
    chunk_size=512,
    chunk_overlap=128,
)


def create_project_knowledge(
        project_dir: str,
        collection_name="project_knowledge_db",
        EMBEDDING_FUNCTION=None
):
    """Creates the Project Knowledge component. Indexes all Python files in the given directory.

    Args:
        project_dir: The path of the project to index.
    """

    print(f"Creating project knowledge for {project_dir!r}")
    repo = (
        project_dir.split("/")[-1]
        if not project_dir.endswith("/")
        else project_dir.split("/")[-2]
    )
    rc = runtime_config.RuntimeConfig()
    persist_directory = os.path.join(rc.runtime_dir, collection_name + "_" + rc.swe_instance_id)  # todo
    print(f"{persist_directory}")
    if os.path.isdir(persist_directory):
        project_knowledge_db = Chroma(
            persist_directory=persist_directory,
            embedding_function=EMBEDDING_FUNCTION,
            collection_name=collection_name,
        )
    else:
        raise FileNotFoundError(
            f"Project knowledge DB not found at {persist_directory}. "
            f"Please build the index before calling create_project_knowledge()."
        )

    # Retrieve docs for log
    total_files, total_funcs = (
        len(project_knowledge_db.get(where={"type": "file"})["ids"]),
        len(project_knowledge_db.get(where={"type": "func"})["ids"]),
    )
    print(
        f"Connected to DB {persist_directory}:{collection_name} containing {total_files} total files and {total_funcs} total func documents."
    )

    project_knowledge_retriever = project_knowledge_db.as_retriever()
    return project_knowledge_retriever, project_knowledge_db


class SearchRelevantFilesInput(BaseModel):
    query: str = Field(
        description="Search query (e.g., issue description, file names, function names, etc.)"
    )
    search_model: Literal["general", "originalbug", "llmsummary"] = Field(
        default="general",
        description=(
            "Query embedding / retrieval mode:\n"
            "- general: Use the raw user query as-is to retrieve relevant code or documentation.\n"
            "- originalbug: The query is a bug report. Bias retrieval toward likely fix locations "
            "(e.g., error sources, input validation, boundary cases, failing modules).\n"
            "- llmsummary: The query is an LLM-generated structured summary of a bug. "
            "Use the summary (often cleaner and more specific) to retrieve the most relevant fix points."
        ),
    )
    k: int = Field(default=10, ge=1, description="Number of top results to return (top-k)")


@tool(args_schema=SearchRelevantFilesInput)
def search_relevant_files(query: str, search_model: str = "general", k: int = 10):
    """
    Given a query, retrieve the most relevant code snippets/files from the vector library.
    """
    if isinstance(k, str):
        k = int(k)
    rc = runtime_config.RuntimeConfig()
    try:
        query_embedding_function = EMBEDDING_FUNCTIONS_BY_SEARCH_MODEL[search_model]
    except KeyError:
        query_embedding_function = EMBEDDING_FUNCTIONS_BY_SEARCH_MODEL["general"]
    project_knowledge_retriever, _ = create_project_knowledge(project_dir=rc.proj_path,
                                                              EMBEDDING_FUNCTION=query_embedding_function)
    relevant_docs = project_knowledge_retriever.invoke(query, k=k)
    full_result = []
    return_string = f"Top {k} most relevant files: \n\n"
    for doc in relevant_docs:
        return_string += doc.metadata["file_path"] + "\n"
        if "func_name" in doc.metadata and doc.metadata["type"] == "func":
            full_result.append(
                {
                    "file_path": doc.metadata["file_path"] + ":" + doc.metadata["func_name"],
                    "code_snippet": doc.page_content,
                }
            )
        else:
            full_result.append(
                {
                    "file_path": doc.metadata["file_path"],
                    "code_snippet": doc.page_content,
                }
            )

    explain_prompt = RELEVANT_FILE_EXPLANATION_SYSTEM_PROMPT.substitute(
        search_term=query, k=k, full_result=full_result
    ).strip()
    generate_explanation = llm.invoke([HumanMessage(explain_prompt)])
    explanations = generate_explanation.content
    return explanations


def summarizer(stage_msgs_processed):
    """Summarize the information of previous chat history to gain addtiional information or remember what you were
    doing."""
    stage_message_keys = list(stage_msgs_processed.keys())
    stage_messages = {}
    for k in stage_message_keys:
        stage_messages[k] = stage_msgs_processed[k]

    summary_prompt = f"Summarize the messages in the following conversation. Be sure to include aggregated details of the key steps and or goals of the message. Include the names of the agents and tools features in the steps. If the agent did not describe its process but used a tool mention the used tool(s). Also include any raw content such as problem statements, solution plans, generated code and or patches if applicable. Be sure to only output your result. Here are the message(s):\n```{stage_messages}\n\nHere is an example of the result:\n```\nStep 1: The user submitted the issue to be resolved.\nStep 2. The supervisor delegated the task to the problem_decoder\nStep 3. The problem_decoder asked the context_manager for help\nStep 4. The context_manager searched for relevant files in the codebase, including file1.py, file2.py.\nStep 5. The context_manager viewed the file file5.py using `view_file_content`.```"

    response = llm.invoke(
        [
            HumanMessage(
                summary_prompt.strip(),
                name="summarizer_agent",
            )
        ]
    )

    summary = response.content

    return summary
